### ISSUE TITLE
Selecting multiple folders at once duplicates their contents when recovered

### ISSUE THREAD

**Issue by burninrubber0** [tdijital/psrecovery-py#2]
When selecting multiple folders in the filesystem and choosing "recover selected", the selected folders' contents are duplicated into the root of the folder chosen to save to. Recovering those same folders one at a time sees no such issues occur.

Tested with a PS3 image ([OG thread](https://www.obscuregamers.com/threads/criterion-games-hdd-image.3329/)) using Python 3.9.7 and Windows 11 21H2.

**Comment by tdijital** [comment]
I think I've resolved this issue with this commit
https://github.com/tdijital/psrecovery-py/commit/02b21cee9d06c05369f9b898f47c3d2294ad97fd

When I get the list of selected items in Tkinters Treeview it was including the children of the first node in the list. I don't really know why. So I now tell the FileWriter to exclude any item that has a parent in the list of items to dump.

**Comment by burninrubber0** [comment]
Confirmed, this is fixed now.
