### ISSUE TITLE
Info differs between initial scan results and results loaded from file

### ISSUE THREAD

**Issue by burninrubber0** [tdijital/psrecovery-py#3]
Pretty much what it says on the tin. The initial scan appears to have all the correct information, while information loaded from the saved scan is missing things. When loaded from a file, there's also a bunch of files at the root that don't appear there in the initial scan.

Tested with a PS3 image ([OG thread](https://www.obscuregamers.com/threads/criterion-games-hdd-image.3329/)) using Python 3.9.7 and Windows 11 21H2.

**Comment by tdijital** [comment]
This should be fixed with this commit https://github.com/tdijital/psrecovery-py/commit/311df7f1cae01eaa20c5a6ad522b8e27833f7d97

Directories that had direct tables spanning beyond a block weren't getting associated with their parent directory when loading from files.
